# Netlify configuration file for Vue 3 with Node.js 21
[build]
  publish = "dist" # Directory where Vite outputs the build files
  command = "npm run build" # Command to build the production version

[build.environment]
  NODE_VERSION = "21" # Specify Node.js version explicitly
  NODE_ENV = "production" # Ensure production environment variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Optional: Specify directory for Netlify serverless functions if any
  directory = "netlify/functions"
